version: "3.8"

services:
  comfyui:
    image: lrev47/my-comfyuipack1:v1
    container_name: comfyui-worker
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - SERVE_API_LOCALLY=true
    ports:
      - "8000:8000"
      - "8188:8188"
    runtime: nvidia
    volumes:
      - ./data/comfyui/output:/comfyui/output
      - ./data/workspace:/workspace
